/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cli.parser;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.PrintStream;

import static org.junit.Assert.assertEquals;

public class ApplicationTest {
    private final InputStream systemIn = System.in;
    private final PrintStream systemOut = System.out;

    private ByteArrayInputStream testIn;
    private ByteArrayOutputStream testOut;

    @Before
    public void setUpOutput() {
        testOut = new ByteArrayOutputStream();
        System.setOut(new PrintStream(testOut));
    }

    private void provideInput(String data) {
        testIn = new ByteArrayInputStream(data.getBytes());
        System.setIn(testIn);
    }

    private String getOutput() {
        return testOut.toString();
    }

    @After
    public void restoreSystemInputOutput() {
        System.setIn(systemIn);
        System.setOut(systemOut);
    }

    @Test
    public void assureApplicationSuccessfullyRunsForCSVToJSON() {
        final String testString = "Name,Address,Postcode,Phone,Credit Limit,Birthday\n\"Johnson, John\",Voorstraat 32,3122gg,020 3849381,1000000,01/01/1987";
        provideInput(testString);
        String[] args = {"csv", "json"};
        Application.main(args);

        assertEquals("[\n" +
                "  {\n" +
                "    \"Credit Limit\": 1000000.0,\n" +
                "    \"Address\": \"Voorstraat 32\",\n" +
                "    \"Phone\": \"020 3849381\",\n" +
                "    \"Birthday\": 536454000000,\n" +
                "    \"Postcode\": \"3122gg\",\n" +
                "    \"Name\": \"Johnson, John\"\n" +
                "  }\n" +
                "]\n" +
                "", getOutput());
    }

    @Test
    public void assureApplicationSuccessfullyRunsForPRNToJSON() {
        final String testString = "Name            Address               Postcode Phone         Credit Limit Birthday\nAnderson, Paul  Dorpsplein 3A         4532 AA  030 3458986       10909300 19651203";
        provideInput(testString);
        String[] args = {"prn", "json"};
        Application.main(args);
        assertEquals("[\n" +
                "  {\n" +
                "    \"Credit Limit\": 109093.0,\n" +
                "    \"Address\": \"Dorpsplein 3A\",\n" +
                "    \"Phone\": \"030 3458986\",\n" +
                "    \"Birthday\": -128739600000,\n" +
                "    \"Postcode\": \"4532 AA\",\n" +
                "    \"Name\": \"Anderson, Paul\"\n" +
                "  }\n" +
                "]\n", getOutput());
    }

    @Test
    public void assureApplicationSuccessfullyRunsForCSVToHTML() {
        final String testString = "Name,Address,Postcode,Phone,Credit Limit,Birthday\n\"Johnson, John\",Voorstraat 32,3122gg,020 3849381,1000000,01/01/1987";
        provideInput(testString);
        String[] args = {"csv", "html"};
        Application.main(args);

        assertEquals("<table>\n" +
                " <tbody>\n" +
                "  <tr>\n" +
                "   <th>Credit Limit</th>\n" +
                "   <th>Address</th>\n" +
                "   <th>Phone</th>\n" +
                "   <th>Birthday</th>\n" +
                "   <th>Postcode</th>\n" +
                "   <th>Name</th>\n" +
                "  </tr>\n" +
                "  <tr>\n" +
                "   <td>1000000.0</td>\n" +
                "   <td>Voorstraat 32</td>\n" +
                "   <td>020 3849381</td>\n" +
                "   <td>Thu Jan 01 00:00:00 CET 1987</td>\n" +
                "   <td>3122gg</td>\n" +
                "   <td>Johnson, John</td>\n" +
                "  </tr>\n" +
                " </tbody>\n" +
                "</table>\n", getOutput());
    }

    @Test
    public void assureApplicationSuccessfullyRunsForPRNToHTML() {
        final String testString = "Name            Address               Postcode Phone         Credit Limit Birthday\nAnderson, Paul  Dorpsplein 3A         4532 AA  030 3458986       10909300 19651203";
        provideInput(testString);
        String[] args = {"prn", "html"};
        Application.main(args);
        assertEquals("<table>\n" +
                " <tbody>\n" +
                "  <tr>\n" +
                "   <th>Credit Limit</th>\n" +
                "   <th>Address</th>\n" +
                "   <th>Phone</th>\n" +
                "   <th>Birthday</th>\n" +
                "   <th>Postcode</th>\n" +
                "   <th>Name</th>\n" +
                "  </tr>\n" +
                "  <tr>\n" +
                "   <td>109093.0</td>\n" +
                "   <td>Dorpsplein 3A</td>\n" +
                "   <td>030 3458986</td>\n" +
                "   <td>Fri Dec 03 00:00:00 CET 1965</td>\n" +
                "   <td>4532 AA</td>\n" +
                "   <td>Anderson, Paul</td>\n" +
                "  </tr>\n" +
                " </tbody>\n" +
                "</table>\n", getOutput());
    }
}
