/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cli.parser;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        Application classUnderTest = new Application();
    }
}
