name: Generate JSON from JSON from CSV and PRN

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew clean customFatJar --no-daemon
    - name: Run script file
      run: |
       cat ./Workbook2.csv| java -jar app/build/libs/all-in-one-jar.jar csv json
       cat ./Workbook2.prn| java -jar app/build/libs/all-in-one-jar.jar prn json
      shell: bash
      
